'use client'

import { useState, useEffect, useCallback } from 'react'
import { createClient } from '@/lib/supabase/client'
import AccountTable from '@/components/ui/AccountTable'
import Modal from '@/components/ui/Modal'
import { Loader2 } from 'lucide-react'

interface ClearingAgent {
  id: string
  agent_id: string
  name: string
  phone: string | null
  company_name: string | null
  email: string | null
  country: string | null
  location: string | null
  is_active: boolean
  created_at: string
}

const blank = { name: '', phone: '', company_name: '', email: '', country: '', location: '' }

export default function ClearingAgentsTab() {
  const [data, setData] = useState<ClearingAgent[]>([])
  const [loading, setLoading] = useState(true)
  const [open, setOpen] = useState(false)
  const [saving, setSaving] = useState(false)
  const [form, setForm] = useState(blank)
  const [editRow, setEditRow] = useState<ClearingAgent | null>(null)

  const load = useCallback(async () => {
    const supabase = createClient()
    const { data: rows } = await supabase
      .from('clearing_agents')
      .select('*')
      .order('created_at', { ascending: false })
    setData(rows ?? [])
    setLoading(false)
  }, [])

  useEffect(() => { load() }, [load])

  function openAdd() {
    setEditRow(null)
    setForm(blank)
    setOpen(true)
  }

  function openEdit(row: ClearingAgent) {
    setEditRow(row)
    setForm({
      name: row.name,
      phone: row.phone ?? '',
      company_name: row.company_name ?? '',
      email: row.email ?? '',
      country: row.country ?? '',
      location: row.location ?? '',
    })
    setOpen(true)
  }

  async function handleSave(e: React.FormEvent) {
    e.preventDefault()
    setSaving(true)
    const supabase = createClient()
    if (editRow) {
      await supabase
        .from('clearing_agents')
        .update({ ...form, updated_at: new Date().toISOString() })
        .eq('id', editRow.id)
    } else {
      await supabase.from('clearing_agents').insert({ ...form })
    }
    setOpen(false)
    setSaving(false)
    load()
  }

  async function handleDelete(row: ClearingAgent) {
    if (!confirm(`Delete clearing agent ${row.name}? This cannot be undone.`)) return
    const supabase = createClient()
    await supabase.from('clearing_agents').delete().eq('id', row.id)
    load()
  }

  const columns = [
    {
      key: 'agent_id', label: 'ID',
      render: (r: ClearingAgent) => (
        <span className="font-mono text-xs bg-gray-100 px-2 py-0.5 rounded text-gray-600">{r.agent_id}</span>
      )
    },
    {
      key: 'name', label: 'Name',
      render: (r: ClearingAgent) => <span className="font-medium text-gray-900">{r.name}</span>
    },
    { key: 'company_name', label: 'Company', render: (r: ClearingAgent) => r.company_name ?? '—' },
    { key: 'phone', label: 'Phone', render: (r: ClearingAgent) => r.phone ?? '—' },
    { key: 'email', label: 'Email', render: (r: ClearingAgent) => r.email ?? '—' },
    { key: 'country', label: 'Country', render: (r: ClearingAgent) => r.country ?? '—' },
    {
      key: 'location', label: 'Location',
      render: (r: ClearingAgent) => (
        <span className="text-gray-500 truncate block max-w-xs">{r.location ?? '—'}</span>
      )
    },
    {
      key: 'is_active', label: 'Status',
      render: (r: ClearingAgent) => (
        <span className={`text-xs font-medium px-2 py-0.5 rounded-full ${r.is_active ? 'bg-green-50 text-green-700' : 'bg-gray-100 text-gray-500'}`}>
          {r.is_active ? 'Active' : 'Inactive'}
        </span>
      )
    },
  ]

  return (
    <>
      <AccountTable
        title="Clearing agents" description="Customs and clearing partners"
        columns={columns} data={data} loading={loading}
        onAdd={openAdd} addLabel="Add clearing agent"
        searchPlaceholder="Search clearing agents..."
        emptyMessage="No clearing agents yet. Add your first agent."
        rowActions={row => [
          { label: 'Edit', onClick: () => openEdit(row) },
          { label: 'Delete', onClick: () => handleDelete(row), danger: true },
        ]}
      />

      <Modal
        open={open}
        onClose={() => setOpen(false)}
        title={editRow ? 'Edit clearing agent' : 'Add clearing agent'}
        description="Agent ID is auto-generated by the system"
      >
        <form onSubmit={handleSave} className="space-y-4">
          <div className="grid grid-cols-2 gap-4">
            <div>
              <label className="block text-sm font-medium text-gray-700 mb-1">
                Name <span className="text-red-400">*</span>
              </label>
              <input
                required
                value={form.name}
                onChange={e => setForm(f => ({ ...f, name: e.target.value }))}
                className="w-full px-3 py-2 text-sm border border-gray-200 rounded-lg focus:outline-none focus:ring-2 focus:ring-brand-500"
                placeholder="Agent name"
              />
            </div>
            <div>
              <label className="block text-sm font-medium text-gray-700 mb-1">Company</label>
              <input
                value={form.company_name}
                onChange={e => setForm(f => ({ ...f, company_name: e.target.value }))}
                className="w-full px-3 py-2 text-sm border border-gray-200 rounded-lg focus:outline-none focus:ring-2 focus:ring-brand-500"
                placeholder="Company name"
              />
            </div>
          </div>
          <div className="grid grid-cols-2 gap-4">
            <div>
              <label className="block text-sm font-medium text-gray-700 mb-1">Phone</label>
              <input
                value={form.phone}
                onChange={e => setForm(f => ({ ...f, phone: e.target.value }))}
                className="w-full px-3 py-2 text-sm border border-gray-200 rounded-lg focus:outline-none focus:ring-2 focus:ring-brand-500"
                placeholder="+234 800 000 0000"
              />
            </div>
            <div>
              <label className="block text-sm font-medium text-gray-700 mb-1">Email</label>
              <input
                type="email"
                value={form.email}
                onChange={e => setForm(f => ({ ...f, email: e.target.value }))}
                className="w-full px-3 py-2 text-sm border border-gray-200 rounded-lg focus:outline-none focus:ring-2 focus:ring-brand-500"
                placeholder="agent@company.com"
              />
            </div>
          </div>
          <div className="grid grid-cols-2 gap-4">
            <div>
              <label className="block text-sm font-medium text-gray-700 mb-1">Country</label>
              <input
                value={form.country}
                onChange={e => setForm(f => ({ ...f, country: e.target.value }))}
                className="w-full px-3 py-2 text-sm border border-gray-200 rounded-lg focus:outline-none focus:ring-2 focus:ring-brand-500"
                placeholder="Country"
              />
            </div>
            <div>
              <label className="block text-sm font-medium text-gray-700 mb-1">Location</label>
              <input
                value={form.location}
                onChange={e => setForm(f => ({ ...f, location: e.target.value }))}
                className="w-full px-3 py-2 text-sm border border-gray-200 rounded-lg focus:outline-none focus:ring-2 focus:ring-brand-500"
                placeholder="Office / port"
              />
            </div>
          </div>
          <div className="flex gap-3 pt-2">
            <button
              type="button"
              onClick={() => setOpen(false)}
              className="flex-1 px-4 py-2 text-sm font-medium border border-gray-200 rounded-lg text-gray-700 hover:bg-gray-50 transition-colors"
            >
              Cancel
            </button>
            <button
              type="submit"
              disabled={saving}
              className="flex-1 px-4 py-2 text-sm font-medium bg-brand-600 text-white rounded-lg hover:bg-brand-700 disabled:opacity-50 transition-colors flex items-center justify-center gap-2"
            >
              {saving ? <><Loader2 size={14} className="animate-spin" /> Saving…</> : editRow ? 'Save changes' : 'Add agent'}
            </button>
          </div>
        </form>
      </Modal>
    </>
  )
}